---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']

ignore: |
  .git/
  clusters/blueberry-k3s/flux-system/gotk-components.yaml
  clusters/blueberry/flux-system/gotk-components.yaml
