# Infrastructure Kustomization
# Deploys platform-level components (monitoring)
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  prune: true
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-prometheus-stack-operator
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: grafana
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: blackbox-exporter
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: speedtest-exporter
      namespace: monitoring
    - apiVersion: apps/v1
      kind: DaemonSet
      name: node-exporter
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: kubernetes-dashboard-kong
      namespace: kubernetes-dashboard
    - apiVersion: apps/v1
      kind: Deployment
      name: kubernetes-dashboard-web
      namespace: kubernetes-dashboard
