# Apps Kustomization
# Deploys application workloads (Matrix stack and future apps)
# Depends on infrastructure being ready (Flux health checks must pass first)
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: infrastructure
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: matrix-postgres
      namespace: matrix
    - apiVersion: apps/v1
      kind: Deployment
      name: synapse
      namespace: matrix
    - apiVersion: apps/v1
      kind: Deployment
      name: element-web
      namespace: matrix
