#ENC[AES256_GCM,data:WRPVELhzYXnaS0a6PUsb284Q,iv:32A0q67iNpMlkKQfhr4G0yrNbzv5qAL7di636lc4lX4=,tag:XQJhNN+hkBy9s8S9ATIAyA==,type:comment]
#
#ENC[AES256_GCM,data:3dRkqroOFlkbc88WfhX/Sq/rGeOYPYRfDJp3z7TSB3KL,iv:lzGQez3m8HtaW0MhNNnytTPnGaQ/i8zFYrbLKO0Qh/8=,tag:V+A1sxD9hEWieXy4UrW2vA==,type:comment]
#ENC[AES256_GCM,data:Oq2bIU5JqjUv+lbU+xnHGexQEp7V7fDN4ZmEYpkIBuDn3nRwxy/pXvVNzDxO2q7IjTRUW1FP8YUzxfGgHNDezcFJQFjoitVFkGD1,iv:jegLEu/L1iv1VC3ZiIwLQc7TLHfUdUDIxrxu8DShwco=,tag:777AEwY82OmagK8DP62svQ==,type:comment]
#ENC[AES256_GCM,data:Mdv7Bv2/XpzOh7hfrS0=,iv:RYU5/3eefW1ZAAId5Cy+5Wfrlm6d1TZGrCerdsTgB20=,tag:BvZYnNkNWAIn1ZkzQ58m0Q==,type:comment]
#ENC[AES256_GCM,data:Qz8F8MMNo0yFbFYVhmKWpqHYm4vCl97pMsJOMKnD89IIs0CepItibx+HpvMr8CB6n7ABH5XtM3SbdP8REWn07Q0lGcDCmpk6sRrrqk16qF++FVI6Ve7W9e9T,iv:UrPhksD5lN9Tb7CZQF5yoyMok8m4OzLiXU13cHWPIbc=,tag:I8su4wxzfuLJ6PlWnEgTtw==,type:comment]
apiVersion: ENC[AES256_GCM,data:VAc=,iv:OxGJ03l3fdxIOkxy+WkBkOcw1wPJ5xBtxfe34id/T5U=,tag:2fRYHQCYjLsFA8jqFbNWYA==,type:str]
kind: ENC[AES256_GCM,data:AEuDRXP7,iv:DdX1J1Nh1h5LIdpKgOblAF/Mx/zVb8pUxBFErD2i2+Y=,tag:tJjBSypX7tExXAcvPZ2F+g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mCbuWGB3q1cCOPdyz+erFso=,iv:ucEQ4cQLYTuCzBTiFU81twuixFF1ls5m2eJa6i5GGv4=,tag:lopH49t6nGajNBrFbcWdrA==,type:str]
    namespace: ENC[AES256_GCM,data:Fz+EHTzRiEzE,iv:A1Ebd4X/cxaWxnkby90Z25LRAWsUMlb2RvIGDWxdTj0=,tag:91EsxooiXdD1zaa3Id2Ovw==,type:str]
type: ENC[AES256_GCM,data:aqpn+tQ0,iv:d1ckJcEHEvQym/wZkknFhKKyKHkBPQvnvHX6FWdt9EI=,tag:DU0GnWf0sfUax4+cEus4rQ==,type:str]
stringData:
    OLLAMA_BASE_URL: ENC[AES256_GCM,data:OR6iG/laX2Y22nce2V2nJUeZzKO81jLrGHk=,iv:FfsSDlwEFmIb9Pr7oum5ygqE3O/eVv1iO++wOSAn/SI=,tag:RA5hyvlecqiAI49G35HCnw==,type:str]
sops:
    age:
        - recipient: age19yjfzcwe6qawzsy24g2j99cd3rcuvp5qaq4a6g4ktuufzs2k8y9qnjyc52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWUw3ZjBYcXNtb1dCM25r
            TFlBdEVqVi9qVUljMXZpWi84dHgxTndTRXdrCkk5cDNvZlpTT0dyclhJQ1QvNFVI
            aUpuRUwxckRSMVhkU21ucGI4UGdqakUKLS0tIHJnZnZvdkplTUJOZEZBZVRuS29W
            NnlISFZ0QnRLMmgyalpNeU5tV0F0M1kK2d129d9bheR8FvRofdGqASxLs4xDK+8x
            9qSewVraV5+0H6uT7cbgvPWI4biYdUKzUnZ4GaCbXbmewVXee6TIDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T10:57:59Z"
    mac: ENC[AES256_GCM,data:Ujkybx5U3JmSpFPqIXGf8iYuXa9TEGNflQN4g+NCUQ5Tn2yARskTEus741ucNInhAOV0ZGtFhoRrbQS1A/bcXNxOVqb680/fdNdUCzwFrIisfEALmo6X3fwnVpEW4ADui/ZqEnbFjRDO2L+e/fOQCsEwcGIzfkOIKI7pU4MQLe0=,iv:C97BgmqJdD6df7EEJNPnpetrqBVWxnXq2etAvVwDTas=,tag:6xeHVM7taPSAvHVkaCEDlg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
