#ENC[AES256_GCM,data:c20NNpRc/gFOgRAoYpNEFDL1+77lzYA+93MUrJHmAtv41b21l1mbJ8nt6kOM97qaUF4cHlEKMk+s9gFmnBIgWxE=,iv:BRgdsdRN3TWnxGwLtWaeIEYFyOBdRWDpz3juG0uWzJM=,tag:IvRsmhkbBq2Xa9uidT1+MA==,type:comment]
#
#ENC[AES256_GCM,data:F+9bo5iRokymLqbafuBdQvVo5wTO872IKXRJ1EZ22+a0zzxKpBYH8H4wJjOwsO1ggeefvqeQ0spZ1uSh9wOXWfX+JJ2nCHqy,iv:AqSLNzfL2gHGZ4zbLrhsNu6FxUqzqCEmLCz7votaSlU=,tag:ipy8X86XE5dczQbqRrdk3Q==,type:comment]
#ENC[AES256_GCM,data:fideDKfpDeHxUex6ugYfml4UTUWBPOHJ7oF+UX0KXs9ZIvbY+HQQ9rfllu7G0cABayK05sWDp3wsbB5nz6Umru/IyQKKaAMm8wN+qkH0KUjN,iv:+os5kj/hdjUXFRQ4vhHIEB0abPVc7j6HQlG3Nrdadkw=,tag:9obJtjxEaBkRKS2mrYnHDQ==,type:comment]
#ENC[AES256_GCM,data:UBZ2etOVJ7zANW2Ip3c734mmSsgZFYB5yXEkT8JmMFvfxqaZeK7qmrmNjiHZJNihh/g/oe2wV+wPbLw=,iv:RDPpq36c4dpZHTPVW5nreNIsYcVTuojDHZuWpquW8Ls=,tag:GpBkkD2GtAXHQU2E/5rB+w==,type:comment]
#
#ENC[AES256_GCM,data:g6V2Ky3hNQk+9voGnFPw3PIfW9kMVeCjlHopN005N+K4ivrcdGNqaLyJz1+AC1MLuyBYHFGzlsfoG1p6Lus4b476riNmK3P2,iv:wYryGICwfeYvA0jcuEeNAJIlPlHqQZAotWhMvbQxQqs=,tag:z8z2hIqYfZEfLVWGE7wqKA==,type:comment]
#ENC[AES256_GCM,data:x01GbnFOpGGNi4ERh/R0+ctzrqUMSTMxLI35UlNnRg9Ycp4k9+N6FSjKjs7IkFVn4s4xWMc=,iv:v5q3OtQM9QR0fHOw7hfVbwRw3liJE9TY1HYwhKBA7Cw=,tag:eXKRCz3zeLfEU6ozXjnOoQ==,type:comment]
#
#ENC[AES256_GCM,data:wDBiDONnRWYGhvvfRZjhEjH3HX+zyTCRHDFa8zuNbdJ0kNFr4BrdjAUK+TTFM9E=,iv:3+JImQm867WKiQbfJ9eefB/fEoWVw3EmxNzgGWHc3jM=,tag:+GOTqWHQt8iGXyohBJHdGQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:40I=,iv:j6HqpwS8P8skrANKJng0q9JNQaKNyHX7MY2XPAck64w=,tag:0ufu4yDfXhGYrHUOrjmx/g==,type:str]
kind: ENC[AES256_GCM,data:uEyx8Jz0,iv:bi20P6XCVJeoseyoUfxlwYl1mipUm5Xqvtuaqy5xGzE=,tag:tmaPKlejvCVWSfxwh+G++A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:f74wcs3LMl7tmBarMuU=,iv:JGKTbjViU1hd6eBilj2KdkE1hCMbmKp1wnxH12ydJxQ=,tag:dSx31lM9Sc5Iwnsx0MXlmw==,type:str]
    namespace: ENC[AES256_GCM,data:cCCzqFIc,iv:2ZO8ouEV+Tzbo7lthVc/Vw/GWUoQO2VoX0/czqJuDhw=,tag:j+CS7IGcOTvNoU3eAr/fRQ==,type:str]
type: ENC[AES256_GCM,data:L3R3CIWk,iv:4Qm5Kl+mXRQ7SyEIGY/HEbm1ZtnQbCI+YREKNH04jlo=,tag:HAeE3GIl0MxREn1KNc7pnw==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:EZ3w6YDCZw==,iv:9U0F50lyuTIsXbFuLCyQsZ5NEvI0KY5kaF9LgMesJjg=,tag:YbhVtAnRIatt2PjwrGtGWw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ndgzTuqkVeVotNaGY5rMlZtzlgGLudQZrQfmS6VyE74AmkqwyaARTyUV4dgfIVBJHrzKEqpKYLYzFees6s6gGQ==,iv:h3G2o0WM3KMQq4k0qh4Xwl1QlRGIuVkXA4XDnjlbvpo=,tag:RpA1YBaWCffGKEbHud1QxQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:iJigf26XdQ==,iv:g+r5UekY8QHTT597sEf3FQdGBvwXUMuYngcIxmImC/Y=,tag:FMwg2bvUix/nMhbZH/8Z1Q==,type:str]
    SYNAPSE_MACAROON_SECRET_KEY: ENC[AES256_GCM,data:XOBid51qkd8PJEyWKn6k+9+INYWbigGK1HrMExjj8v2qRu+R1q/oDLhrSnxAGi8Jh8LQU86wkgiTWPOXbG5OUA==,iv:k4j6Rr4reNpM4sV/hnh1XGATYx7pAgHlQLoWRXOC89Y=,tag:y4yOyT4umWhT0nXfKmnPDA==,type:str]
    SYNAPSE_REGISTRATION_SHARED_SECRET: ENC[AES256_GCM,data:OhHw2bOGEb6JsIPIqPgOLpMCQ/Ie2UzP6tEJnG5wf/Yz5MEkHZaK61rAZwZo+eUKnQZu9xDQqaEWlYrTD3FuQA==,iv:sjV3SpM81qDTCCL8lLeGEnrace7ZzlAlD3O7XTTMshE=,tag:fclHbqG0kmLenW42h2SFwg==,type:str]
    SYNAPSE_FORM_SECRET: ENC[AES256_GCM,data:QwkKF2uZ4uwF8jrYUJV7n1nqzTGDn6kqG2VefRYvz3xtydB6WiIUZ97Roqu0LN6F+zJa7484MtrlLNdLgHq6Ug==,iv:b7n8iAbWoXpCqBUkr84SuCiEqguaL+Uu9QmMmh9ZK+g=,tag:49aVV2Dq/AB3a+i04RMjIA==,type:str]
sops:
    age:
        - recipient: age19yjfzcwe6qawzsy24g2j99cd3rcuvp5qaq4a6g4ktuufzs2k8y9qnjyc52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVWo5QjUzaURCaHJCT3Y4
            NHk5V2drRFkyRnF2QUtYUkF5NUtBYTNaU21RCmxsR3AzNmxZYVVaTmwvM3pHUUc0
            ZGZ3d2t2WHZ2N3Q4V01HVGplS0g3Z1UKLS0tIEhmZjk1VTVPT0NmSTl0dWIyZzhK
            aGQyaTRTRGdsYzFpYUhCNEdzVXh4UncKIUz+vbpCWHHiWItDQT6WnmQ6rJQ0xFaq
            OaNnNRX7c/V00ua27ClgeVp6x2oQ4U/UgpEVlhLmYHRBHA1+nB4hCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T12:33:12Z"
    mac: ENC[AES256_GCM,data:XNQIcuJ0SSrBVtX9+hV1HAW3DmzcjlCwAxUPU6pKwSBJMzMoLIs5aSBVTm1yzyqQUrKCRBU9cy7NcafLEA+FGkUHgYKdh/fays4k/kSeOULebqMyDpz8iQIARrRt0LZpq8MpGl57N+D34irq990047AefTxLM4rtLeNl2xEVLgQ=,iv:23EksZEw3vzh7kguj9ZbQk1/uK32fHToFXQ7TP648gg=,tag:sRgHpnWucqz42LntErrHwQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
