# PostgreSQL for Matrix Synapse
#
# Provides a dedicated PostgreSQL instance for Synapse's database backend.
# Single-replica, no HA - appropriate for edge/SBC deployment.
#
# Credentials are defined in apps/matrix/matrix-secrets.yaml (SOPS-encrypted).
# See MATRIX.md for full setup instructions.
---
# PVC for PostgreSQL data directory.
# Uses default StorageClass (K3S local-path provisioner on blueberry-k3s).
# USB-attached storage - avoid excessive write amplification.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-postgres-data
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-postgres
  namespace: matrix
  labels:
    app: matrix-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matrix-postgres
  template:
    metadata:
      labels:
        app: matrix-postgres
    spec:
      containers:
        - name: postgres
          # docker.io/library/postgres:16.6-alpine
          # Alpine variant for smaller image footprint on aarch64
          image: docker.io/library/postgres:16.6-alpine
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            # PGDATA must be a subdirectory of the mount point (Kubernetes requirement)
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            # Synapse requires C locale/collation and UTF8 encoding
            - name: POSTGRES_INITDB_ARGS
              value: "--lc-collate=C --lc-ctype=C --encoding=UTF8"
          envFrom:
            - secretRef:
                name: matrix-secrets
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - synapse
                - -d
                - synapse
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - synapse
                - -d
                - synapse
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: matrix-postgres-data
---
# ClusterIP only - PostgreSQL is not exposed outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: matrix-postgres
  namespace: matrix
  labels:
    app: matrix-postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: matrix-postgres
