# Synapse Matrix Homeserver
#
# Official Matrix homeserver by Element (ghcr.io/element-hq/synapse).
# Configured with PostgreSQL backend and persistent data volume.
# Media store and signing key are persisted in the synapse-data PVC.
#
# Configuration (including secrets) is in apps/matrix/synapse-config.yaml (SOPS-encrypted).
# See MATRIX.md for full setup instructions.
---
# PVC for Synapse data: signing key, media store, and other runtime state.
# Uses default StorageClass (K3S local-path provisioner on blueberry-k3s).
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-data
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  namespace: matrix
  labels:
    app: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      # Postgres must be ready before Synapse starts
      initContainers:
        - name: wait-for-postgres
          image: docker.io/library/postgres:16.6-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h matrix-postgres -U synapse; do
                echo "Waiting for PostgreSQL..."; sleep 2;
              done
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
      containers:
        - name: synapse
          # ghcr.io/element-hq/synapse:v1.147.1
          # Includes security fix CVE-2026-24044 (insecure signing key federation block)
          image: ghcr.io/element-hq/synapse:v1.147.1
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: /conf/homeserver.yaml
          ports:
            - name: http
              containerPort: 8008
              protocol: TCP
          volumeMounts:
            # Config files from ConfigMap (read-only)
            - name: config
              mountPath: /conf/homeserver.yaml
              subPath: homeserver.yaml
              readOnly: true
            - name: config
              mountPath: /conf/log.config
              subPath: log.config
              readOnly: true
            # Persistent data: signing key, media store
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8008
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8008
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: synapse-config
        - name: data
          persistentVolumeClaim:
            claimName: synapse-data
---
# NodePort 30067 → container port 8008 (Matrix client/federation API)
apiVersion: v1
kind: Service
metadata:
  name: synapse
  namespace: matrix
  labels:
    app: synapse
spec:
  type: NodePort
  ports:
    - name: http
      port: 8008
      targetPort: 8008
      nodePort: 30067
      protocol: TCP
  selector:
    app: synapse
