apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-exporter
  namespace: monitoring
  labels:
    app: speedtest-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-exporter
  template:
    metadata:
      labels:
        app: speedtest-exporter
    spec:
      containers:
        - name: speedtest-exporter
          # Note: Digest not available from upstream registry (miguelndecarvalho/speedtest-exporter)
          # Validated ARM64 support via manifest inspection (see commit ece9ae3)
          image: miguelndecarvalho/speedtest-exporter:v0.5.1
          ports:
            - name: http
              containerPort: 9798
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9798
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9798
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  namespace: monitoring
  labels:
    app: speedtest-exporter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9798
      targetPort: 9798
      protocol: TCP
  selector:
    app: speedtest-exporter
